#ifndef WALKING_STABILIZATION_CONTROLLER__VISIBILITY_CONTROL_H_
#define WALKING_STABILIZATION_CONTROLLER__VISIBILITY_CONTROL_H_

// This logic was borrowed (then namespaced) from the examples on the gcc wiki:
//     https://gcc.gnu.org/wiki/Visibility

#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define WALKING_STABILIZATION_CONTROLLER_EXPORT __attribute__ ((dllexport))
    #define WALKING_STABILIZATION_CONTROLLER_IMPORT __attribute__ ((dllimport))
  #else
    #define WALKING_STABILIZATION_CONTROLLER_EXPORT __declspec(dllexport)
    #define WALKING_STABILIZATION_CONTROLLER_IMPORT __declspec(dllimport)
  #endif
  #ifdef WALKING_STABILIZATION_CONTROLLER_BUILDING_LIBRARY
    #define WALKING_STABILIZATION_CONTROLLER_PUBLIC WALKING_STABILIZATION_CONTROLLER_EXPORT
  #else
    #define WALKING_STABILIZATION_CONTROLLER_PUBLIC WALKING_STABILIZATION_CONTROLLER_IMPORT
  #endif
  #define WALKING_STABILIZATION_CONTROLLER_PUBLIC_TYPE WALKING_STABILIZATION_CONTROLLER_PUBLIC
  #define WALKING_STABILIZATION_CONTROLLER_LOCAL
#else
  #define WALKING_STABILIZATION_CONTROLLER_EXPORT __attribute__ ((visibility("default")))
  #define WALKING_STABILIZATION_CONTROLLER_IMPORT
  #if __GNUC__ >= 4
    #define WALKING_STABILIZATION_CONTROLLER_PUBLIC __attribute__ ((visibility("default")))
    #define WALKING_STABILIZATION_CONTROLLER_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define WALKING_STABILIZATION_CONTROLLER_PUBLIC
    #define WALKING_STABILIZATION_CONTROLLER_LOCAL
  #endif
  #define WALKING_STABILIZATION_CONTROLLER_PUBLIC_TYPE
#endif

#endif  // WALKING_STABILIZATION_CONTROLLER__VISIBILITY_CONTROL_H_
